### ISSUE TITLE
Automatic embedding images - relative paths

### ISSUE THREAD

**Issue by badsyntax** [nodemailer/mailcomposer#15]
Hi

I have a query with this line of code: https://github.com/andris9/mailcomposer/blob/master/lib/mailcomposer.js#L1381

Why is embedded images restricted to absolute URLs or paths? I'm pretty sure it can handle relative paths fine. (I've just tried it, no problems!)

So really I'm just curious why this restriction is in place? It would be very useful to allow for relative paths!

Thanks!

**Comment by ogonkov** [comment]
Why not set it to relative to final destination? I think it's would be expected behaviour in most cases.

**Comment by 4e1ovek** [comment]
Maybe this piece of code will help you to build the right path to the images:
http://pastebin.com/JkTCqzkV
