### ISSUE TITLE
Custum headers long

### ISSUE THREAD

**Issue by 4e1ovek** [nodemailer/mailcomposer#60]
[ENG]
When working with long headings, namely `List-Unsubscribe` when you transmit letters to the MTA Postfix and the subsequent signature with opendkim, there is a problem with DKIM. The signature is not correct and is identified as `fail`. Add titles to mailcomposer, without processing library `buildmail `impossible. While solved so:

[RUS]
При работе с длинными заголовками, а именно `List-Unsubscribe` при передачи письма в MTA Postfix и последующей подписью с помощью opendkim, возникает проблема с DKIM. Подпись оказывается не корректной и идентифицируется как `fail`. Добавить заголовки в mailcomposer, без обработки библиотекой `buildmail` нельзя. Пока решил так:

`buildmail\src\buildmail.js:`
```javascript
    MimeNode.prototype.buildHeaders = function() {

		...

		if (key == 'List-Unsubscribe') {
			headers.push(key + ': ' + value);
		} else {
			headers.push(libmime.foldLines(key + ': ' + value, 76));
		}
        return headers.join('\r\n');
    };
```

**Comment by andris9** [comment]
This is possible in v3.3.0. Instead of a string value ofr a header, use the following syntax:

```
var mail = {
    ...,
    headers: {
        'Normal-Header': 'this line gets encoded and folded if needed',
        'Prepared-Header': {
            prepared: true,
            value: 'This value is added as is, no encoding or wrapping is applied to it'
        }
    }
}
```
