### ISSUE TITLE
issue on attachment.fileName 

### ISSUE THREAD

**Issue by Fruneng** [nodemailer/mailcomposer#61]
In mailparser, it was `fileName`,  and in here it was `filename`

https://github.com/nodemailer/mailcomposer/blob/master/lib/mailcomposer.js#L251

**Comment by andris9** [comment]
Use older version of mailcomposer to have `fileName`

    npm install mailcomposer@0.2.12

See the docs for 0.2.12 [here](https://github.com/nodemailer/mailcomposer/tree/a16700b52865b5b6aa1fed3874ae6d8fd7ada353)
