### ISSUE TITLE
Not standard way for headers in attachment

### ISSUE THREAD

**Issue by ricardopolo** [nodemailer/mailcomposer#62]
Hi. In 221875baf5afdcbb4a18a43875de421dcc44c7b6 you allow to pass headers to an attachment.

You are receiving the headers in this way: `{'X-My-Header': 'value'}` but not in the way ` [{key: "X-Key-Name", value: "val1"}, {key: "X-Key-Name", value: "val2"}]` that you allow in the message.

Would you accept the same format for headers in attachments please?

Ps. Are you accepting it also in alternatives, right?

Thanks you! 
cc @andris9

**Comment by andris9** [comment]
Yes, I plan to make the headers of message, attachments and alternatives compatible

**Comment by andris9** [comment]
Works in v3.2.1
