### ISSUE TITLE
Change the sinikael word

### ISSUE THREAD

**Issue by ricardopolo** [nodemailer/mailcomposer#63]
Hey.

I found in the multipart message that you created you select the boundary like `boundary="----sinikael-?=_1-14531655450770.6491799491923302"`

So, what is the word sinikael? Would we be able to change it?
(I dont have a particular reason for that, just found a little bit strange word, so would be nice to allow it change in the options of the build function)

Thanks

Cc @andris9

**Comment by andris9** [comment]
I'm fine as it already is, no plans to change anything regarding this string
