### ISSUE TITLE
How to sing DKIM?

### ISSUE THREAD

**Issue by vermaslal** [nodemailer/mailcomposer#64]
Hi,

I want to sign our own DKIM for all mails. Is there any method for this module?

**Comment by andris9** [comment]
Use [dkim-signer](https://github.com/andris9/dkim-signer) module tor it. First, generate the rfc822 message with mailcomposer (you can't stream, you need to build it into a Buffer or a string), then create the signature and the prepend the signature to the rfc822 message

```javascript
var mail = mailcomposer({from: '...', ...});
mail.build(function(err, message){
    message = message.toString();
    var signature = DKIMSign(message, dkimOptions);
    message = signature + "\r\n" + message;
    console.log(message);
});
```

**Comment by vermaslal** [comment]
Thanks. It's working fine.
