### ISSUE TITLE
HTML content attached as att00001.htm

### ISSUE THREAD

**Issue by 4e1ovek** [nodemailer/mailcomposer#66]
Hello. 
The first thing I want to say thank you for your excellent program. Very helps, if you want to send a few thousand emails.
Use `mailcomposer@2.1.0` in conjunction with `smtp-connection@1.3.1` and `dkim-signer@0.2.0`. From time to time, a problem occurs when the HTML content of the letter be attached as a file `att00001.htm` and the text content is lost completely. This behavior is rare, and when re-sending already is not repeated. I can't catch the reason why.

The encoding is `7bit`. Today switched to `base64`, perhaps this will rectify the situation.

Source email: http://pastebin.com/tLcxV60U
Source worker.js: http://pastebin.com/KatHhAcZ

**Comment by andris9** [comment]
Seems like the message gets parsed and recomposed by your MTA. Try to copy the message before sending it to a file or variable and compare it with the message that is actually sent to see what was changed.
