### ISSUE TITLE
Question about integration with nodemailer-attachments-parser

### ISSUE THREAD

**Issue by killmenot** [nodemailer/mailcomposer#69]
Hi @andris9

I recently wrote [nodemailer-postmark-transport](https://github.com/killmenot/nodemailer-postmark-transport) and then added attachments support to it. To parse nodemailer attachments object I extracted some mailcomposer's private methods (`_getAttachments` and `_processDataUrl `) to a new package [nodemailer-attachments-parser](https://github.com/killmenot/nodemailer-attachments-parser) that I used in postmark transport

Do you want me to re use it in `mailcomposer` and send you PR? I also can transfer this repository to nodemailer organization if needed

**Comment by andris9** [comment]
I think that the best option would be to make these methods public by removing the underscore and also documenting these methods in README. There's not much point keeping a copy of the same code in different repos. If you could make these changes in mailcomposer and create a PR then it would be great

**Comment by killmenot** [comment]
Agree regarding the point about same code. I will do it when be more available than now

**Comment by killmenot** [comment]
What your thoughts about [parsing data URL](https://github.com/killmenot/nodemailer-attachments-parser/blob/master/lib/attachments-parser.js#L104)? I think it more easier than it was before. `parse ` method is the same.

**Comment by andris9** [comment]
I guess it is more robust as it checks the url validity but in generally I oppose micro-dependencies, I would rather update the parser function in mailcomposer instead of adding two new small dependencies to the project.

**Comment by killmenot** [comment]
no problem. I see your point
