### ISSUE TITLE
Unable to send excel file properly

### ISSUE THREAD

**Issue by prafulc** [nodemailer/mailcomposer#71]
I am using mailComposer 0.1.1, Its there in meteor. Here is my code:

```
Email.send({
          to:  email ,
          from: email,
          subject: "Excel Attachment",
          attachments: [
            {
                filename: "report.xlsx",
                contents: file,
                contentType: 'xlsx'
                /*,
                encoding: 'binary',
                contentType: 'application/octet-stream'*/
            }
          ]
```
It is sending attachment but unable to open that file.

**Comment by andris9** [comment]
Your content type for the excel file is invalid, you should probably drop it and let mailcomposer to auto-detect it from file extension

**Comment by prafulc** [comment]
I have tried that too. But got same result. Unable to open the file.
I am using xlsx module for NPM
```
XLSX = Meteor.npmRequire('xlsx')
file  = XLSX.write(wb,wopts);
```
Also I have tried with `contents: new Buffer(file,'utf-8')`

**Comment by prafulc** [comment]
Thanks for help. I have solved it. Its data should be Buffer with type binary
