### ISSUE TITLE
Can we use nodemailer plugins when using mailcomposer

### ISSUE THREAD

**Issue by ricardopolo** [nodemailer/mailcomposer#72]
Is it possible to use nodemailer plugins (like the one who generates text plain version) when using mailcomposer (and not nodemailer)?

I can understand plugins like the one to signs with DKIM wont work, but the ones to modify the message will work?

Thanks

**Comment by andris9** [comment]
No, there is no automatic plugin handling. This is not something too complex anyway, you can find the plugin handling code [here](https://github.com/nodemailer/nodemailer/blob/master/lib/nodemailer.js#L339-L364). Just do something similar.
