### ISSUE TITLE
Blank spaces as breaklines in message

### ISSUE THREAD

**Issue by ricardopolo** [nodemailer/mailcomposer#73]
I am creating a message using mailcomposer, and the sending the generated stream using Haraka.

However I am having this issue:
https://github.com/haraka/Haraka/issues/1583

Thay could be relate to mailcomposer?

Thank you so much for your help @andris9

**Comment by andris9** [comment]
I answered in the Haraka issue thread. Btw is this issue related to outbound sending and not inbound? I suggest you to check out another project of mine for outbound sending – [ZoneMTA](https://github.com/zone-eu/zone-mta).

**Comment by ricardopolo** [comment]
@andris9 that projecs look cool!! I'll take  a look
