### ISSUE TITLE
How to compose an email with html body and pdf attachment 

### ISSUE THREAD

**Issue by rockysimkonis** [nodemailer/mailcomposer#75]
I have been trying to use mailcomposer to send an email with html text in the body of email and a pdf attachment. 

When I send it it gets wrapped in a base64 encoding such as below the code snippet.

However, if I comment out the html property, the email received includes the pdf as an attachment and not a base64 string as shown below code snippet.

Current implementation: 

```javascript
const mail = mailcomposer({
            from: "test@test.com",
            to: emailTo,
            subject: "Subject",
            html: '<p>Hello World!</p>',
            attachments: [
                {
                    filename: 'proposal.pdf',
                    content: fs.createReadStream(__dirname + "\\" + "proposal.pdf"),
                    contentType: 'application/pdf',
                }
            ]
});

 mail.build(function(err, message) {
            // Write HTML to file.
            fs.writeFile(filePath, message, 'utf-8', function (err) {
                if(err){
                    console.log("Oops something went wrong! Please try sending test email again.");
                }
            });
  });
```

------sinikael-?=_1-Thu Nov 03 2016 15:45:19 GMT-0500 (Central Daylight Time)0.14578919341172192
Content-Type: text/html
Content-Transfer-Encoding: 7bit

<p>Hello World!</p>
------sinikael-?=_1-Thu Nov 03 2016 15:45:19 GMT-0500 (Central Daylight Time)0.14578919341172192
Content-Type: application/pdf; name=proposal.pdf
Content-Disposition: attachment; filename=proposal.pdf
Content-Transfer-Encoding: base64

**Comment by andris9** [comment]
You are using some kind of date library that messes up Date.now(), try to remove it as lot of modules expect Date.now() to return a timestamp number not a date string. In your example the invalid date timestamp breaks mime boundaries and resulting email is invalid

**Comment by rockysimkonis** [comment]
@andris9 Thanks, you were right! Removing the date.js library used resolved the issue. Went with native Javascript Date prototype without using any library and it worked as expected.
