### ISSUE TITLE
message built by mailcomposer(...).build() has no bcc header.

### ISSUE THREAD

**Issue by ohjames** [nodemailer/mailcomposer#77]
The docs show bcc being used but the raw body returned by `build()` does not contain the `Bcc:` header. In a much earlier version of mailcomposer I had to use the `keepBcc` option to avoid it being stripped, but it no longer seems to be supported.

**Comment by ohjames** [comment]
Have to pass the `keepBcc` option to `BuildMail`'s constructor (via it's second argument) for it to work. I can open a PR easily, is someone around to accept it?

**Comment by andris9** [comment]
Here's how Nodemailer handles BCC header: https://github.com/andris9/nodemailer-sendmail-transport/blob/master/src/sendmail-transport.js#L61

**Comment by ohjames** [comment]
Can't get that to work.
